apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.monitor.enabled }}
      initContainers:
      - name: init-ai-downloader
        image: appropriate/curl
        args:
          - "-fsSL"
          - "-o"
          - "/tmp/data/applicationinsights.jar"
          - {{ .Values.monitor.jar | quote }}
        volumeMounts:
        - name: init-script
          mountPath: /tmp/data
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8089
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ if .Values.monitor.enabled }}
          volumeMounts:
          - name: init-script
            mountPath: /tmp/data
          env:
          - name: JAVA_ARGS
            value: "-javaagent:/tmp/data/applicationinsights.jar"
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            value: {{ .Values.monitor.aiConnectionString | quote }}
          {{ end }}
      {{ if .Values.monitor.enabled }}
      volumes:
      - name: init-script
        emptyDir: {}
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
