apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: demo.contoso.com
    http:
      paths:
      - path: /demo(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "demo.fullname" . }}
            port:
              number: 80